import "./globals.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";

import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });
const akira = localFont({
  src: [{ path: "../../public/fonts/Akira.ttf", weight: "normal" }],
  variable: "--font-akira",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          .font-akira {
            font-family: ${akira.style.fontFamily.replaceAll("'", "")};
          }
        `}</style>
      </head>
      <body className={`${inter.className} bg-text text-text`}>{children}</body>
    </html>
  );
}
